### ISSUE TITLE
오류 페이지

### ISSUE THREAD

**Issue by hyeontack5** [2022-Summer-Bootcamp-Team-F/Face-Change#4]

**Comment by Dong-Seung-hyeon** [comment]
기본 틀구조와 버튼(Link) 기능구현 완료

**Comment by Dong-Seung-hyeon** [comment]
<img width="1440" alt="스크린샷 2022-07-19 오후 5 32 50" src="https://user-images.githubusercontent.com/94991070/180636280-d5e34f4d-4570-40ad-ba30-6793fce51f97.png">
